language: node_js
node_js:
    - '0.12'
install: npm install
script: ./push.sh
branches:
  only:
      - blog
env:
  global:
    secure: "jLRqByHLGw6NIDhU2ocl6QonB79YQTXb9/s7Xd/foOB5JLV53TNvMfM5BctsUTTvsQOVe6pytjh3M3zQhi9A+UJeSCV3FGDl0QJ4ZK2fk3bFDbTjuLCR0SaMJILfULnXxUuirvzZr46+thxmU7Awp1WuGtcmy10AXcTLDCx/t8o="
